#!/usr/bin/env bash
# generate-env.sh — derives all the-M secrets from a local master passphrase
# Usage: ./generate-env.sh
# Reads:  secrets.local  (never committed)
# Writes: .env           (never committed)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/secrets.local"
ENV_FILE="$SCRIPT_DIR/.env"
EXAMPLE_FILE="$SCRIPT_DIR/secrets.local.example"

if [ ! -f "$SECRETS_FILE" ]; then
  echo "secrets.local not found. Creating from example..."
  cp "$EXAMPLE_FILE" "$SECRETS_FILE"
  echo ""
  echo "ACTION REQUIRED:"
  echo "  Edit secrets.local and replace THE_M_MASTER_SECRET with a strong passphrase."
  echo "  Then re-run this script."
  echo ""
  echo "  Generate one with:  openssl rand -hex 32"
  exit 1
fi

MASTER=$(grep "^THE_M_MASTER_SECRET=" "$SECRETS_FILE" | cut -d= -f2 | tr -d '[:space:]')
if [ -z "$MASTER" ]; then
  echo "ERROR: THE_M_MASTER_SECRET not found in secrets.local" && exit 1
fi
if [ "$MASTER" = "replace-this-with-a-strong-random-passphrase" ]; then
  echo "ERROR: Set a real passphrase in secrets.local first." && exit 1
fi

# HMAC-SHA256 derivation
derive() {
  echo -n "the-m:$1" | openssl dgst -sha256 -hmac "$MASTER" | awk '{print $2}'
}

DB_PASS=$(derive "db-password")
SECRET_KEY=$(derive "secret-key")
JWT_SECRET=$(derive "jwt-secret")
LIVEKIT_API_KEY="APIkey$(derive "livekit-api-key" | cut -c1-20)"
LIVEKIT_API_SECRET="$(derive "livekit-api-secret")"

cat > "$ENV_FILE" <<EOF
# the-M environment — generated by generate-env.sh
# DO NOT COMMIT — this file is git-ignored

# ─── Database ────────────────────────────────────────────────
THE_M_DB_USER=them
THE_M_DB_PASSWORD=$DB_PASS

# ─── Security ────────────────────────────────────────────────
THE_M_SECRET_KEY=$SECRET_KEY
THE_M_JWT_SECRET=$JWT_SECRET
THE_M_REDIS_PASSWORD=

# ─── LLM (add your key here — not derived) ───────────────────
ANTHROPIC_API_KEY=

# ─── Agent-specific API keys (override ANTHROPIC_API_KEY per agent group) ────
# Leave blank to fall back to ANTHROPIC_API_KEY
DOCU_WRITER_ANTHROPIC_API_KEY=
DEBATE_ANTHROPIC_API_KEY=
SECURITY_SCANNER_ANTHROPIC_API_KEY=

# ─── Network ─────────────────────────────────────────────────
THE_M_HOSTNAME=them.example.com
THE_M_UI_HOSTNAME=them-ui.example.com
THE_M_BRIDGE_WS_URL=ws://localhost:8001
THE_M_CORS_ORIGINS=http://localhost:3200

# ─── Application ─────────────────────────────────────────────
APP_ENV=development
LOG_LEVEL=INFO

# ─── Voice / LiveKit ─────────────────────────────────────────
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
LIVEKIT_PUBLIC_URL=ws://localhost:8088/livekit
EOF

echo ".env generated successfully."
echo ""
echo "DB password : ${DB_PASS:0:8}..."
echo "Secret key  : ${SECRET_KEY:0:8}..."
echo "JWT secret  : ${JWT_SECRET:0:8}..."
echo "LiveKit key : ${LIVEKIT_API_KEY:0:12}..."
echo ""
echo "Add your ANTHROPIC_API_KEY to .env if you need LLM calls."
