# generate-env.ps1 — derives all the-M secrets from a local master passphrase
# Usage: .\generate-env.ps1
# Reads:  secrets.local  (never committed)
# Writes: .env           (never committed)

$ErrorActionPreference = "Stop"

$secretsFile = Join-Path $PSScriptRoot "secrets.local"
$envFile     = Join-Path $PSScriptRoot ".env"
$exampleFile = Join-Path $PSScriptRoot "secrets.local.example"

if (-not (Test-Path $secretsFile)) {
    Write-Host "secrets.local not found. Creating from example..."
    Copy-Item $exampleFile $secretsFile
    Write-Host ""
    Write-Host "ACTION REQUIRED:"
    Write-Host "  Edit secrets.local and replace THE_M_MASTER_SECRET with a strong passphrase."
    Write-Host "  Then re-run this script."
    Write-Host ""
    Write-Host "  Generate one with:"
    Write-Host "    python -c `"import secrets; print(secrets.token_hex(32))`""
    exit 1
}

# Load master secret
$raw = Get-Content $secretsFile -Raw
if ($raw -notmatch "THE_M_MASTER_SECRET=(.+)") {
    Write-Error "THE_M_MASTER_SECRET not found in secrets.local"
    exit 1
}
$master = $Matches[1].Trim()
if ($master -eq "replace-this-with-a-strong-random-passphrase") {
    Write-Error "You must set a real passphrase in secrets.local first."
    exit 1
}

# HMAC-SHA256 derivation function
function Derive-Secret {
    param([string]$purpose)
    $hmac = New-Object System.Security.Cryptography.HMACSHA256
    $hmac.Key = [System.Text.Encoding]::UTF8.GetBytes($master)
    $bytes = $hmac.ComputeHash([System.Text.Encoding]::UTF8.GetBytes("the-m:$purpose"))
    return ([System.BitConverter]::ToString($bytes) -replace "-","").ToLower()
}

$dbPass           = Derive-Secret "db-password"
$secretKey        = Derive-Secret "secret-key"
$jwtSecret        = Derive-Secret "jwt-secret"
$livekitApiKey    = "APIkey$((Derive-Secret 'livekit-api-key').Substring(0,20))"
$livekitApiSecret = Derive-Secret "livekit-api-secret"

$envContent = @"
# the-M environment — generated by generate-env.ps1
# DO NOT COMMIT — this file is git-ignored

# ─── Database ────────────────────────────────────────────────
THE_M_DB_USER=them
THE_M_DB_PASSWORD=$dbPass

# ─── Security ────────────────────────────────────────────────
THE_M_SECRET_KEY=$secretKey
THE_M_JWT_SECRET=$jwtSecret
THE_M_REDIS_PASSWORD=

# ─── LLM (add your key here — not derived) ───────────────────
ANTHROPIC_API_KEY=

# ─── Network ─────────────────────────────────────────────────
THE_M_HOSTNAME=them.example.com
THE_M_UI_HOSTNAME=them-ui.example.com
THE_M_BRIDGE_WS_URL=ws://localhost:8001
THE_M_CORS_ORIGINS=http://localhost:3200

# ─── Application ─────────────────────────────────────────────
APP_ENV=development
LOG_LEVEL=INFO

# ─── Voice / LiveKit ─────────────────────────────────────────
LIVEKIT_API_KEY=$livekitApiKey
LIVEKIT_API_SECRET=$livekitApiSecret
LIVEKIT_PUBLIC_URL=ws://localhost:8088/livekit
"@

Set-Content -Path $envFile -Encoding utf8 -Value $envContent
Write-Host ".env generated successfully."
Write-Host ""
Write-Host "DB password : $($dbPass.Substring(0,8))..."
Write-Host "Secret key  : $($secretKey.Substring(0,8))..."
Write-Host "JWT secret  : $($jwtSecret.Substring(0,8))..."
Write-Host "LiveKit key : $($livekitApiKey.Substring(0,12))..."
Write-Host ""
Write-Host "Add your ANTHROPIC_API_KEY to .env if you need LLM calls."
