package crypto

import (
	"encoding/base64"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ─── Known test vectors ───────────────────────────────────────────────────────
//
// Generated by Python inside them-bridge using a test-only secret.
// Command used (see WAVE7_IMPLEMENTATION_REPORT.md for full derivation):
//
//	docker exec them-bridge python3 -c "
//	  import base64, hashlib, hmac as hmaclib, struct
//	  from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
//	  from cryptography.hazmat.backends import default_backend
//	  ..."
//
// SECRET_KEY used: "wave7-test-secret-do-not-use-in-prod"
// These are test-only values. NEVER use or print a real production secret.
//
// Deterministic vector parameters:
//   - IV:        0102030405060708090a0b0c0d0e0f10  (fixed)
//   - Timestamp: 1700000000                        (fixed)
//   - Verified:  Python Fernet.decrypt() returns b"test-api-key-wave7-phase1" ✓

const (
	testSecretKey = "wave7-test-secret-do-not-use-in-prod"

	// sha256(testSecretKey) hex — verified by Python hashlib.sha256
	wantKeyHex = "7117484aa9e4a6816ed76ec393a870f61dcf65b795a01d8c35a3f580a16abfe5"

	knownPlaintext = "test-api-key-wave7-phase1"

	// knownToken: the deterministic Fernet token produced by manual construction
	// and verified against Python's Fernet.decrypt().
	knownToken = "gAAAAABlU_EAAQIDBAUGBwgJCgsMDQ4PENSEfjZhbp7TUUrlX2VX4Etcgk5ljOeuEzUqszUGnzW309NBYudvQUNjUK41tv5em0yiWzwl2UxYFRyd2ZV4o24="

	// knownStoredValue is "enc:" + knownToken — what Python's encrypt_value() stores.
	knownStoredValue = "enc:" + knownToken
)

// ─── Key derivation ──────────────────────────────────────────────────────────

func TestDeriveKey_Length(t *testing.T) {
	key := DeriveKey(testSecretKey)
	assert.Len(t, key, 32, "DeriveKey must return 32 bytes")
}

func TestDeriveKey_KnownSHA256(t *testing.T) {
	// sha256("wave7-test-secret-do-not-use-in-prod") verified by Python
	key := DeriveKey(testSecretKey)
	got := hex.EncodeToString(key)
	assert.Equal(t, wantKeyHex, got)
}

func TestDeriveKey_DifferentInputsDifferentKeys(t *testing.T) {
	k1 := DeriveKey("secret-a")
	k2 := DeriveKey("secret-b")
	assert.NotEqual(t, k1, k2)
}

// ─── Known vector: Python encrypts → Go decrypts ─────────────────────────────

func TestDecrypt_KnownPythonVector(t *testing.T) {
	key := DeriveKey(testSecretKey)
	got, err := Decrypt(key, knownToken)
	require.NoError(t, err, "decrypting known Python vector must succeed")
	assert.Equal(t, knownPlaintext, string(got))
}

func TestDecryptStored_KnownPythonVector(t *testing.T) {
	key := DeriveKey(testSecretKey)
	got, err := DecryptStored(key, knownStoredValue)
	require.NoError(t, err)
	assert.Equal(t, knownPlaintext, got)
}

// ─── Round-trip: Go encrypts → Go decrypts ───────────────────────────────────

func TestEncryptDecrypt_RoundTrip(t *testing.T) {
	key := DeriveKey(testSecretKey)
	plaintext := "sk-ant-api03-abcdefghijklmnopqrstuvwxyz0123456789"

	token, err := Encrypt(key, []byte(plaintext))
	require.NoError(t, err)
	assert.NotEmpty(t, token)

	got, err := Decrypt(key, token)
	require.NoError(t, err)
	assert.Equal(t, plaintext, string(got))
}

func TestEncryptStoredDecryptStored_RoundTrip(t *testing.T) {
	key := DeriveKey(testSecretKey)
	plaintext := "sk-ant-api03-wave7-roundtrip-test"

	stored, err := EncryptStored(key, plaintext)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(stored, "enc:"), "stored value must have enc: prefix")

	got, err := DecryptStored(key, stored)
	require.NoError(t, err)
	assert.Equal(t, plaintext, got)
}

// Multiple calls with the same key must produce different ciphertexts (random IV).
func TestEncrypt_RandomIV(t *testing.T) {
	key := DeriveKey(testSecretKey)
	tok1, err1 := Encrypt(key, []byte("same-plaintext"))
	tok2, err2 := Encrypt(key, []byte("same-plaintext"))
	require.NoError(t, err1)
	require.NoError(t, err2)
	assert.NotEqual(t, tok1, tok2, "two encryptions must produce different tokens (random IV)")
}

// ─── Edge cases: plaintext content ───────────────────────────────────────────

func TestEncryptDecrypt_ShortPlaintext(t *testing.T) {
	// "hello" — 5 chars, ≤8 chars (masked as "****" in LLMProvider responses)
	key := DeriveKey(testSecretKey)
	tok, err := Encrypt(key, []byte("hello"))
	require.NoError(t, err)
	got, err := Decrypt(key, tok)
	require.NoError(t, err)
	assert.Equal(t, "hello", string(got))
}

func TestEncryptDecrypt_ExactlyOneBlock(t *testing.T) {
	// 16-byte plaintext — exactly one AES block, requires a full padding block added
	key := DeriveKey(testSecretKey)
	plain := "1234567890123456"
	tok, err := Encrypt(key, []byte(plain))
	require.NoError(t, err)
	got, err := Decrypt(key, tok)
	require.NoError(t, err)
	assert.Equal(t, plain, string(got))
}

func TestEncryptDecrypt_LongAPIKey(t *testing.T) {
	// Typical API key — 62 chars
	key := DeriveKey(testSecretKey)
	plain := "sk-ant-api03-abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLM"
	tok, err := Encrypt(key, []byte(plain))
	require.NoError(t, err)
	got, err := Decrypt(key, tok)
	require.NoError(t, err)
	assert.Equal(t, plain, string(got))
}

func TestEncryptDecrypt_Unicode(t *testing.T) {
	// "café" — 5 UTF-8 bytes
	key := DeriveKey(testSecretKey)
	plain := "café"
	tok, err := Encrypt(key, []byte(plain))
	require.NoError(t, err)
	got, err := Decrypt(key, tok)
	require.NoError(t, err)
	assert.Equal(t, plain, string(got))
}

// ─── Empty plaintext guard ────────────────────────────────────────────────────

func TestEncrypt_EmptyPlaintext(t *testing.T) {
	// Python's encrypt_value returns the empty string unchanged — a guard at the
	// call site, not inside Fernet. Go matches this by rejecting empty plaintext
	// with ErrInvalidToken so callers use nil DB columns for "no key" state.
	key := DeriveKey(testSecretKey)
	_, err := Encrypt(key, []byte{})
	assert.ErrorIs(t, err, ErrInvalidToken)
}

// ─── Wrong key ───────────────────────────────────────────────────────────────

func TestDecrypt_WrongKey(t *testing.T) {
	goodKey := DeriveKey(testSecretKey)
	badKey := DeriveKey("totally-different-secret")

	tok, err := Encrypt(goodKey, []byte("my-plaintext"))
	require.NoError(t, err)

	_, err = Decrypt(badKey, tok)
	assert.ErrorIs(t, err, ErrHMACMismatch)
}

// ─── Tampered HMAC ───────────────────────────────────────────────────────────

func TestDecrypt_TamperedHMAC(t *testing.T) {
	key := DeriveKey(testSecretKey)
	tok, err := Encrypt(key, []byte("secret"))
	require.NoError(t, err)

	raw, err := base64.URLEncoding.DecodeString(tok)
	require.NoError(t, err)
	// Flip the last byte of the HMAC.
	raw[len(raw)-1] ^= 0xff
	tampered := base64.URLEncoding.EncodeToString(raw)

	_, err = Decrypt(key, tampered)
	assert.ErrorIs(t, err, ErrHMACMismatch)
}

// ─── Tampered ciphertext ──────────────────────────────────────────────────────

func TestDecrypt_TamperedCiphertext(t *testing.T) {
	key := DeriveKey(testSecretKey)
	tok, err := Encrypt(key, []byte("another-secret"))
	require.NoError(t, err)

	raw, err := base64.URLEncoding.DecodeString(tok)
	require.NoError(t, err)
	// Flip one byte inside the ciphertext region (after version+timestamp+IV = 25 bytes).
	raw[25] ^= 0x01
	tampered := base64.URLEncoding.EncodeToString(raw)

	_, err = Decrypt(key, tampered)
	// HMAC covers the ciphertext — any modification must be detected there.
	assert.ErrorIs(t, err, ErrHMACMismatch)
}

// ─── Invalid base64 ───────────────────────────────────────────────────────────

func TestDecrypt_InvalidBase64(t *testing.T) {
	key := DeriveKey(testSecretKey)
	_, err := Decrypt(key, "not-valid-base64!!!")
	assert.ErrorIs(t, err, ErrInvalidToken)
}

// ─── Truncated token ─────────────────────────────────────────────────────────

func TestDecrypt_TruncatedToken(t *testing.T) {
	key := DeriveKey(testSecretKey)
	// 4 bytes — far below minTokenLen (73 bytes).
	short := base64.URLEncoding.EncodeToString([]byte{0x80, 0x00, 0x01, 0x02})
	_, err := Decrypt(key, short)
	assert.ErrorIs(t, err, ErrInvalidToken)
}

// ─── Wrong version byte ───────────────────────────────────────────────────────

func TestDecrypt_WrongVersionByte(t *testing.T) {
	key := DeriveKey(testSecretKey)
	tok, err := Encrypt(key, []byte("versioned"))
	require.NoError(t, err)

	raw, err := base64.URLEncoding.DecodeString(tok)
	require.NoError(t, err)
	raw[0] = 0x7f // wrong version
	bad := base64.URLEncoding.EncodeToString(raw)

	_, err = Decrypt(key, bad)
	assert.ErrorIs(t, err, ErrInvalidToken)
}

// ─── DecryptStored passthrough for non-prefixed values ────────────────────────

func TestDecryptStored_NoPrefix_PassThrough(t *testing.T) {
	// Python's decrypt_value returns value as-is when prefix is absent.
	key := DeriveKey(testSecretKey)
	got, err := DecryptStored(key, "not-encrypted-at-all")
	require.NoError(t, err)
	assert.Equal(t, "not-encrypted-at-all", got)
}

func TestDecryptStored_Empty_PassThrough(t *testing.T) {
	key := DeriveKey(testSecretKey)
	got, err := DecryptStored(key, "")
	require.NoError(t, err)
	assert.Equal(t, "", got)
}

// ─── PKCS7 padding ───────────────────────────────────────────────────────────

func TestPKCS7Pad_Unpad_Identity(t *testing.T) {
	cases := []struct {
		name  string
		input []byte
	}{
		{"single-byte", []byte("a")},
		{"half-block", []byte("12345678")},
		{"full-block", []byte("1234567890123456")}, // 16 bytes → adds a full 16-byte padding block
		{"long", []byte("abcdefghijklmnopqrstuvwxyz")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			padded := pkcs7Pad(tc.input, 16)
			assert.Equal(t, 0, len(padded)%16, "padded length must be multiple of 16")
			assert.Greater(t, len(padded), len(tc.input), "padded must be longer than input")

			unpadded, err := pkcs7Unpad(padded)
			require.NoError(t, err)
			assert.Equal(t, tc.input, unpadded)
		})
	}
}

func TestPKCS7Unpad_ZeroPadByte(t *testing.T) {
	// A pad byte of 0 is invalid per PKCS7.
	data := make([]byte, 16) // all zeroes
	_, err := pkcs7Unpad(data)
	assert.Error(t, err)
}

func TestPKCS7Unpad_InconsistentBytes(t *testing.T) {
	// Last byte says padding is 3, but other bytes are wrong.
	data := make([]byte, 16)
	data[13] = 0x01
	data[14] = 0x02
	data[15] = 0x03
	_, err := pkcs7Unpad(data)
	assert.Error(t, err)
}

// ─── Key size validation ──────────────────────────────────────────────────────

func TestEncrypt_WrongKeySize(t *testing.T) {
	_, err := Encrypt([]byte("tooshort"), []byte("plaintext"))
	assert.Error(t, err)
}

func TestDecrypt_WrongKeySize(t *testing.T) {
	_, err := Decrypt([]byte("tooshort"), knownToken)
	assert.Error(t, err)
}

// ─── EncryptStored prefix ────────────────────────────────────────────────────

func TestEncryptStored_HasPrefix(t *testing.T) {
	key := DeriveKey(testSecretKey)
	stored, err := EncryptStored(key, "sk-ant-something")
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(stored, "enc:"),
		"EncryptStored output must start with enc:")
}

// TestDecryptStored_InvalidToken verifies that a token with the enc: prefix but
// invalid content returns ErrHMACMismatch or ErrInvalidToken (not a panic).
func TestDecryptStored_InvalidToken(t *testing.T) {
	key := DeriveKey(testSecretKey)
	_, err := DecryptStored(key, "enc:notavalidfernettokengAAAAABad")
	assert.Error(t, err)
}
