entryPoints:
  web:
    address: ":8088"
  traefik:
    address: ":8089"

providers:
  docker:
    exposedByDefault: false
    network: them-network
    constraints: "Label(`traefik-instance`,`them`)"

api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog: {}
