package temporal

// PythonOrchestrationInput is the wire-format input for the Python
// OrchestrationWorkflow. Field names mirror the Python OrchestrationInput
// dataclass exactly so the Temporal SDK's JSON codec round-trips correctly.
//
// RunID is pre-generated by Go (via newID in the handler) and passed to the
// Python workflow so it publishes all events to them:dash:run:{RunID}:tokens —
// the exact channel Go subscribes to before calling ExecuteWorkflow. This
// eliminates the need for a context-channel bootstrap handshake.
// Python falls back to workflow.uuid4() when RunID is absent (Python-native callers).
type PythonOrchestrationInput struct {
	OrchestratorName string         `json:"orchestrator_name"`
	UserMessage      string         `json:"user_message"`
	UserID           int64          `json:"user_id"`
	TokenPayload     map[string]any `json:"token_payload"`
	SessionID        string         `json:"session_id"`
	ContextID        string         `json:"context_id"`
	RunID            string         `json:"run_id,omitempty"`
	EntryPointSlug   string         `json:"entry_point_slug,omitempty"`
	HistoryWindow    int            `json:"history_window"`
	TokensUsedCarry  int            `json:"tokens_used_carry"`
	IterationCarry   int            `json:"iteration_carry"`
	Depth            int            `json:"depth"`
}
